Repository empowerplan/epp-app, pull requests merged in 2024-03, with the labels that each got.

#19 keep detail panel open on slider value change
  CHANGELOG.md
  digiplan/static/js/sliders.js
Labels: low priority :arrow_down_small:

#22 Update django_oemof to version v0.17.0 and init env var
  .envs/.local/.django
  poetry.lock
  pyproject.toml
Labels: enhancement :rocket:

#46 PV map controls get focus and highlighted when selecting PV details
  digiplan/map/views.py
  digiplan/static/js/sliders.js
  digiplan/static/scss/app.scss
  digiplan/static/scss/layouts/_blinking.scss
  digiplan/templates/components/layer_box.html
Labels: enhancement :rocket:

#50 Feature/wind areas legend
  CHANGELOG.md
  digiplan/static/scss/layouts/_panel.scss
  digiplan/templates/forms/panel_energy.html
Labels: enhancement :rocket:, frontend :rainbow:
